version: 2

updates:
  # Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "threatflux-team"
    assignees:
      - "threatflux-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
      - "dependabot"
    # Only allow patch and minor updates by default
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Allow security updates for major versions
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "threatflux-team"
    assignees:
      - "threatflux-team"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "dependabot"

  # Node.js dependencies (if package.json exists)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "threatflux-team"
    assignees:
      - "threatflux-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "nodejs"
      - "dependabot"
    # Only patch and minor updates for Node.js
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    versioning-strategy: "increase"

  # Docker dependencies (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "threatflux-team"
    assignees:
      - "threatflux-team"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "dependabot"

  # Terraform dependencies (if Terraform files exist)
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "threatflux-team"
    assignees:
      - "threatflux-team"
    commit-message:
      prefix: "chore(terraform)"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "dependabot"