# Configuration for cargo-deny
# See: https://embarkstudios.github.io/cargo-deny/

[licenses]
# List of explicitly allowed licenses
# All other licenses are denied by default in version 2 format
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "CC0-1.0",
    # Additional licenses needed for package-security dependencies
    "bzip2-1.0.6",        # libbz2-rs-sys
    "Zlib",               # libz-rs-sys, zlib-rs
    "MPL-2.0",            # option-ext (Mozilla Public License)
    "CDLA-Permissive-2.0", # webpki-roots
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# Specific crates to deny
deny = [
    # Prefer rustls over OpenSSL for security and portability
    { name = "openssl", use-instead = "rustls" },
    { name = "openssl-sys", use-instead = "rustls" },
    
    # Security-sensitive crates we want to avoid
    { name = "native-tls", use-instead = "rustls" },
]

# Allow certain crates to have multiple versions (useful for build dependencies)
skip = [
    # Allow duplicate getrandom versions (v0.2 and v0.3)
    { name = "getrandom" },
    # Allow duplicate hashbrown versions (transitive dependency conflicts)
    { name = "hashbrown" },
    # Allow duplicate thiserror versions (ecosystem transition)
    { name = "thiserror" },
    { name = "thiserror-impl" },
    # Allow duplicate WASI versions (different targets)
    { name = "wasi" },
    # Allow duplicate Windows versions (different targets/features)
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]

# Skip certain crates during duplicate detection entirely
skip-tree = []

[advisories]
# Use version 2 of the advisories configuration format
version = 2

# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The URL(s) of the advisory databases to use
db-urls = ["https://github.com/RustSec/advisory-db"]

# The lint level for unmaintained crates (all, workspace, transitive, none)
unmaintained = "all"

# The lint level for crates that have been yanked from their source registry (allow, warn, deny)
yanked = "deny"

# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
    # Add any specific advisories to ignore here
    # "RUSTSEC-2023-0001",
]

[sources]
# Lint level for when multiple versions of the same crate are detected
unknown-registry = "warn"

# Lint level for when a crate from a git repository is detected
unknown-git = "warn"

# List of allowed registries
allow-registry = [
    "https://github.com/rust-lang/crates.io-index"
]

# List of allowed Git repositories
allow-git = [
    # Add any specific git dependencies here if needed
]