name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Before submitting, please verify the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of the file scanner
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command: `./file-scanner ...`
        2. Use these options: `...`
        3. Observe the error: `...`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages)
      placeholder: |
        Error message or unexpected output:
        ```
        paste error here
        ```
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: File Scanner Version
      description: What version of the file scanner are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust are you using? (run `rustc --version`)
      placeholder: "rustc 1.87.0 (e4ff1013a 2025-04-21)"

  - type: textarea
    id: file-info
    attributes:
      label: File Information
      description: Information about the file being analyzed (if applicable)
      placeholder: |
        - File type: (e.g., ELF binary, PE executable, text file)
        - File size: (approximate)
        - File format: (if known)
        - Can you share the file? (yes/no)

  - type: textarea
    id: logs
    attributes:
      label: Debug Output
      description: Run with verbose logging and paste relevant output
      placeholder: |
        Run: `RUST_LOG=debug ./file-scanner [options]`
        
        ```
        paste debug output here
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Configuration details
        - Related issues
        - Screenshots (if applicable)
        - Workarounds you've tried