blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ThreatFlux/threatflux-package-security/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: mailto:security@threatflux.com
    about: Report security vulnerabilities privately via email