name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Before submitting, please verify the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature would be useful to other users, not just my specific use case
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New analysis capability
        - Performance improvement
        - CLI enhancement
        - MCP server enhancement
        - Output format improvement
        - Integration with external tools
        - Security enhancement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: |
        I'm always frustrated when...
        Currently, there's no way to...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        I would like to see...
        The feature should work by...
        It could be implemented as...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I also considered...
        Another approach could be...
        Existing tools do this by...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be beneficial
      placeholder: |
        Use case 1: Security analysts could...
        Use case 2: Researchers could...
        Use case 3: Automation tools could...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: |
        This could be implemented by...
        It might require changes to...
        Similar features exist in...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to help implement this feature
        - label: I can provide testing and feedback
        - label: I can help with documentation
        - label: I can provide example files or test cases

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, mockups, or examples
      placeholder: |
        - Links to similar features in other tools
        - Screenshots or mockups
        - Example command-line interfaces
        - References to relevant standards or specifications