name: 🔒 Security Vulnerability
description: Report a security vulnerability (use for non-critical issues only)
title: "[Security] "
labels: ["security", "high-priority", "needs-triage"]
assignees: ["threatflux-security"]

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **IMPORTANT:** 
        - For **critical security vulnerabilities**, please report privately via email: security@threatflux.com
        - Only use this template for **low-risk** security issues that can be discussed publicly
        - If you're unsure about the severity, err on the side of caution and email us privately

  - type: checkboxes
    id: severity-check
    attributes:
      label: Severity Confirmation
      description: Please confirm this is appropriate for public reporting
      options:
        - label: This is a LOW-RISK security issue that can be discussed publicly
          required: true
        - label: This does NOT involve remote code execution, privilege escalation, or data exposure
          required: true
        - label: I understand that critical vulnerabilities should be reported privately via email
          required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Information disclosure (low-risk)
        - Input validation issue
        - Dependency vulnerability
        - Configuration issue
        - Documentation security issue
        - CI/CD security issue
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue in detail
      placeholder: |
        Describe the vulnerability:
        - What component is affected?
        - What is the potential impact?
        - How was it discovered?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: |
        1. Set up environment: ...
        2. Run command: ...
        3. Observe behavior: ...
        4. Security impact: ...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Confidentiality impact: ...
        - Integrity impact: ...
        - Availability impact: ...
        - Scope of impact: ...
    validations:
      required: true

  - type: input
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: "v1.0.0 - v1.2.3, or 'all versions', or 'latest'"
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this vulnerability?
      placeholder: |
        Possible fixes:
        - Input validation improvements
        - Configuration changes
        - Code modifications
        - Dependency updates

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Environment where the vulnerability was discovered
      placeholder: |
        - Operating System: ...
        - File Scanner Version: ...
        - Rust Version: ...
        - Build Configuration: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
      placeholder: |
        - Related CVEs or security advisories
        - References to security standards
        - Proof of concept (if safe to share)
        - Timeline for disclosure

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure
      description: Responsible disclosure agreement
      options:
        - label: I agree to follow responsible disclosure practices
          required: true
        - label: I will not publicly exploit this vulnerability
          required: true
        - label: I will work with the maintainers to resolve this issue
          required: true