name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  # Validate release conditions
  validate-release:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.0
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            IS_PRERELEASE="${{ github.event.inputs.prerelease }}"
          else
            VERSION="${{ github.ref_name }}"
            IS_PRERELEASE="false"
            if [[ "$VERSION" =~ -[a-zA-Z] ]]; then
              IS_PRERELEASE="true"
            fi
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "Release version: $VERSION (prerelease: $IS_PRERELEASE)"

      - name: Validate version format
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?$ ]]; then
            echo "Invalid version format: $VERSION"
            echo "Expected format: v1.2.3 or v1.2.3-alpha.1"
            exit 1
          fi

  # Run full test suite before release
  pre-release-tests:
    name: Pre-Release Tests
    needs: validate-release
    uses: ./.github/workflows/ci.yml

  # Generate library package
  build-library-package:
    name: Build Library Package
    needs: [validate-release, pre-release-tests]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: release-package

      - name: Build library
        run: cargo build --all-features --release

      - name: Package library crate
        run: cargo package --allow-dirty

      - name: Create source archive
        run: |
          mkdir -p release-package
          cp target/package/threatflux-package-security-*.crate release-package/
          cp README.md CHANGELOG.md LICENSE* release-package/ 2>/dev/null || true
          
          VERSION="${{ needs.validate-release.outputs.version }}"
          CARGO_VERSION="${VERSION#v}"
          
          cd release-package
          tar -czf threatflux-package-security-${{ needs.validate-release.outputs.version }}-src.tar.gz *
          cd ..
          mv release-package/threatflux-package-security-${{ needs.validate-release.outputs.version }}-src.tar.gz .

      - name: Generate checksums
        run: |
          shasum -a 256 threatflux-package-security-${{ needs.validate-release.outputs.version }}-src.tar.gz > threatflux-package-security-${{ needs.validate-release.outputs.version }}-src.tar.gz.sha256

      - name: Upload release package
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: library-package
          path: |
            threatflux-package-security-${{ needs.validate-release.outputs.version }}-src.tar.gz
            threatflux-package-security-${{ needs.validate-release.outputs.version }}-src.tar.gz.sha256
            target/package/threatflux-package-security-*.crate
          retention-days: 5

  # Generate changelog
  generate-changelog:
    name: Generate Changelog
    needs: validate-release
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.0
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | head -2 | tail -1 || echo "")
          CURRENT_TAG="${{ needs.validate-release.outputs.version }}"
          
          echo "Generating changelog from $PREVIOUS_TAG to $CURRENT_TAG"
          
          # Generate changelog content
          CHANGELOG="## Changes in $CURRENT_TAG\n\n"
          
          if [[ -n "$PREVIOUS_TAG" ]]; then
            # Get commits since last tag
            COMMITS=$(git log --pretty=format:"- %s" "$PREVIOUS_TAG..HEAD" | head -50)
            if [[ -n "$COMMITS" ]]; then
              CHANGELOG+="### Commits\n$COMMITS\n\n"
            fi
            
            # Get merged PRs (simplified)
            PRS=$(git log --pretty=format:"%s" --grep="Merge pull request" "$PREVIOUS_TAG..HEAD" | sed 's/Merge pull request #\([0-9]*\) from .*/- PR #\1/' | head -20)
            if [[ -n "$PRS" ]]; then
              CHANGELOG+="### Pull Requests\n$PRS\n\n"
            fi
            
            # Full changeset link
            CHANGELOG+="**Full Changeset**: https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...$CURRENT_TAG"
          else
            CHANGELOG+="Initial release of ThreatFlux Package Security Library\n\n"
            CHANGELOG+="### Features\n"
            CHANGELOG+="- NPM package security analysis and vulnerability detection\n"
            CHANGELOG+="- Python package security analysis with setup.py risk assessment\n"
            CHANGELOG+="- Java package analysis and vulnerability scanning\n"
            CHANGELOG+="- Typosquatting detection across all package ecosystems\n"
            CHANGELOG+="- Supply chain security assessment\n"
            CHANGELOG+="- Unified package security framework\n"
            CHANGELOG+="- Async processing for high performance\n"
            CHANGELOG+="- Comprehensive vulnerability database with auto-updates\n"
          fi
          
          # Save changelog to file and output
          echo -e "$CHANGELOG" > RELEASE_CHANGELOG.md
          
          # For GitHub output, we need to handle multiline properly
          {
            echo 'changelog<<EOF'
            echo -e "$CHANGELOG"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Upload changelog
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: changelog
          path: RELEASE_CHANGELOG.md
          retention-days: 5

  # Create GitHub release
  create-release:
    name: Create GitHub Release
    needs: [validate-release, build-library-package, generate-changelog]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.0

      - name: Download all artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.7
        with:
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: ${{ needs.validate-release.outputs.version }}
          name: ${{ needs.validate-release.outputs.version }}
          body: ${{ needs.generate-changelog.outputs.changelog }}
          prerelease: ${{ needs.validate-release.outputs.is_prerelease == 'true' }}
          files: |
            threatflux-package-security-*.tar.gz
            threatflux-package-security-*.tar.gz.sha256
            threatflux-package-security-*.crate
          generate_release_notes: true
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Update library version
  update-version:
    name: Update Library Version
    needs: [validate-release, create-release]
    runs-on: ubuntu-latest
    if: needs.validate-release.outputs.is_prerelease == 'false'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Update library version
        run: |
          VERSION="${{ needs.validate-release.outputs.version }}"
          # Remove 'v' prefix for cargo
          CARGO_VERSION="${VERSION#v}"
          
          # Update package version
          cargo set-version "$CARGO_VERSION"

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml
          git diff --staged --quiet || git commit -m "chore: bump version to ${{ needs.validate-release.outputs.version }}"
          git push

  # Publish to crates.io (optional, requires API token)
  publish-crates:
    name: Publish to Crates.io
    needs: [validate-release, create-release]
    runs-on: ubuntu-latest
    if: needs.validate-release.outputs.is_prerelease == 'false' && vars.PUBLISH_TO_CRATES == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish library to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "Publishing threatflux-package-security crate..."
          cargo publish --allow-dirty || echo "Failed to publish crate (may already exist)"

  # Notify on release completion
  notify-completion:
    name: Notify Release Completion
    needs: [validate-release, create-release, update-version]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Release Summary
        run: |
          echo "# Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ needs.validate-release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Prerelease:** ${{ needs.validate-release.outputs.is_prerelease }}" >> $GITHUB_STEP_SUMMARY
          echo "**Release Status:** ${{ needs.create-release.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Release URL:** https://github.com/${{ github.repository }}/releases/tag/${{ needs.validate-release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ needs.create-release.result }}" == "success" ]]; then
            echo "✅ Release created successfully!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Release creation failed!" >> $GITHUB_STEP_SUMMARY
          fi